dist: trusty
sudo: required

language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

services:
  - mongodb
  - rabbitmq

env:
  - OMNICORE_VERSION="0.0.11.1-rel"

before_install: ./scripts/travis.sh

before_script:
  - eval $(./scripts/setup_omni.sh)
  - echo $PROPERTY_ID

script: sbt ++$TRAVIS_SCALA_VERSION test:compile &&
    sbt ++$TRAVIS_SCALA_VERSION specialk/test &&
    sbt ++$TRAVIS_SCALA_VERSION agentService/test &&
    sbt ++$TRAVIS_SCALA_VERSION "gloseval/run gencert --self-signed" &&
    sbt ++$TRAVIS_SCALA_VERSION gloseval/test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/omnicore-$OMNICORE_VERSION

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.sbt -name "*.lock" -type f -delete

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0be5e8019da24eb59119
    on_success: change
    on_failure: always
    on_start: never
