sudo: required

language: scala

scala:
  - 2.10.6

jdk:
  - oraclejdk7

services:
  - mongodb
  - rabbitmq
  - memcached

script: sbt ++$TRAVIS_SCALA_VERSION test:compile &&
    sbt ++$TRAVIS_SCALA_VERSION specialk/test &&
    sbt ++$TRAVIS_SCALA_VERSION agentService/test &&
    sbt ++$TRAVIS_SCALA_VERSION gloseval/test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.sbt -name "*.lock" -type f -delete

before_install: make
